### ISSUE TITLE
Website is inaccessible. 

### ISSUE THREAD

**Issue by iphyer** [THUNLP-AIPoet/StylisticPoetry#1]
As the title.

<img width="936" alt="Screen Shot 2019-07-02 at 8 14 45 PM" src="https://user-images.githubusercontent.com/1913891/60556262-163d6e00-9d06-11e9-8d85-3f867dc2c8ce.png">

**Comment by XiaoyuanYi** [comment]
We use https instead of http. Please explicitly add https in the URL as 'https://jiuge.thunlp.cn/'. If you access our website via a mobile phone, it is HTTP by default. Please check the URL.

**Comment by XiaoyuanYi** [comment]
> As the title.
> 
> <img alt="Screen Shot 2019-07-02 at 8 14 45 PM" width="936" src="https://user-images.githubusercontent.com/1913891/60556262-163d6e00-9d06-11e9-8d85-3f867dc2c8ce.png">

We use https instead of http. Please explicitly add https in the URL as 'https://jiuge.thunlp.cn/'. If you access our website via a mobile phone, it is HTTP by default. Please check the URL.

**Comment by XiaoyuanYi** [comment]
> As the title.
> 
> <img alt="Screen Shot 2019-07-02 at 8 14 45 PM" width="936" src="https://user-images.githubusercontent.com/1913891/60556262-163d6e00-9d06-11e9-8d85-3f867dc2c8ce.png">

We use https instead of http. Please explicitly add https in the URL as 'https://jiuge.thunlp.cn/'. If you access our website via a mobile phone, it is HTTP by default. Please check the URL.

**Comment by iphyer** [comment]
Thx
