### ISSUE TITLE
how to make text_train.pkl, text_dev.pkl and text_test.pkl?

### ISSUE THREAD

**Issue by cauchyhk** [THUNLP-AIPoet/StylisticPoetry#13]
I am confused by the README.md. I do not see anywhere close to have text_train.pkl, text_dev.pkl and text_test.pkl. Under /data, make_corpus.py does not work either, as it asks for loading cPickle?

**Comment by XiaoyuanYi** [comment]
@cauchyhk  Hi, you can build these data files by using make_corpus.py, which is provided in StylisticPoetry/data/.  We also give an example of the input data file,  poems.txt, in the same directory.
