### ISSUE TITLE
程序问题

### ISSUE THREAD

**Issue by TobeyLi** [THUNLP-AIPoet/StylisticPoetry#2]
您好，看了您的code,发现有些内容没有提供，但是也没有说这个文件的格式，请问一下，在Yun.py文件中的totalpoemlist方法中，您使用到了data/poemcorpus/totaljiantipoems_change.txt这个文件，这个文件是什么样的格式的，如果方便的话请加qq讨论：1147413415  谢谢您的解答。

**Comment by yangchengbupt** [comment]
您好，我们在对应目录中新提供了一个该文件的样例。

**Comment by TobeyLi** [comment]
谢谢您的解答，还有一个文件也麻烦您给出一个example。就是在生成模型的时候，generate_base.py初始化时候使用了一个/data/other/DuplicateCheckLIb.txt文件，这个文件是缺少的，麻烦您给出一个示例。麻烦您了。

**Comment by yangchengbupt** [comment]
我们又添加了一些文件或文件输入样例。因为数据主体的诗库没有版权公开，所以暂时只能这样，请见谅。

**Comment by TobeyLi** [comment]
谢谢您
