### ISSUE TITLE
程序运行时缺少很多文件

### ISSUE THREAD

**Issue by BIGKUANG** [THUNLP-AIPoet/StylisticPoetry#3]
您好，作者。我对你的研究这一块非常感兴趣，但是，在运行您的代码时，发现缺少很多文件。如果作者能分享这些文件，会对很多人受益。谢谢~~

**Comment by yangchengbupt** [comment]
您好，我们现在提供了输入文件或者输入文件的样例。因为数据主体的诗库没有版权公开，所以暂时只能这样，请见谅。
