### ISSUE TITLE
文件中ivocab.pkl和vocab.pkl 文件怎末得到？？？

### ISSUE THREAD

**Issue by DJxuelei** [THUNLP-AIPoet/StylisticPoetry#5]

**Comment by lhw0003** [comment]
请问你联系作者得到了那两个文件了吗？

**Comment by yangchengbupt** [comment]
字表文件已经上传

**Comment by lhw0003** [comment]
请问text_train.pkl可以上传一下吗？

**Comment by yangchengbupt** [comment]
我们的诗歌corpus是从搜韵网协商拿到的，因为版权问题暂时无法提供诗歌数据，比如text_train.所以只有代码，可以关注下这个github的组，未来的工作中应该会放出

**Comment by VasiliShi** [comment]
> 我们的诗歌corpus是从搜韵网协商拿到的，因为版权问题暂时无法提供诗歌数据，比如text_train.所以只有代码，可以关注下这个github的组，未来的工作中应该会放出

版权？中华古诗竟然有版权

**Comment by yangchengbupt** [comment]
> > 我们的诗歌corpus是从搜韵网协商拿到的，因为版权问题暂时无法提供诗歌数据，比如text_train.所以只有代码，可以关注下这个github的组，未来的工作中应该会放出
> 
> 版权？中华古诗竟然有版权

可能表述不当，但对方大概是这意思，你可以自己去爬或者用其他公开的数据
