### ISSUE TITLE
缺少pkl文件

### ISSUE THREAD

**Issue by moonABC3** [THUNLP-AIPoet/StylisticPoetry#8]
缺少yun.pkl文件

**Comment by wangjiangnan** [comment]
有的文件并不缺少只是不在指定目录下，有两个pkl文件根本就没有；
代码运行环境希望作者给出，项目generate文件需要python 3环境，但是make_corpus文件需要python 2。

**Comment by Twizwei** [comment]
I also found those two files missing...
Hope you guys upload these two files

**Comment by moonABC3** [comment]
> I also found those two files missing...
> Hope you guys upload these two files

yun.pkl文件在https://github.com/xiaoyuanYi/WMPoetry

**Comment by yangchengbupt** [comment]
我们的诗歌corpus是从搜韵网协商拿到的，因为版权问题暂时无法提供诗歌数据，比如text_train

**Comment by wangjiangnan** [comment]
> 我们的诗歌corpus是从搜韵网协商拿到的，因为版权问题暂时无法提供诗歌数据，比如text_train

text_train不是在make_corpus生成的吗？代码已经跑通了，现在不缺文件了。

**Comment by wangjiangnan** [comment]
> 我们的诗歌corpus是从搜韵网协商拿到的，因为版权问题暂时无法提供诗歌数据，比如t

**Comment by XiaoyuanYi** [comment]
> 缺少yun.pkl文件

新的yun.pkl文件已经重命名为pingshui_amb.pkl， 整合到了我们的[THU-CRRD](https://github.com/THUNLP-AIPoet/Datasets/tree/master/CRRD) 数据集中。
